#!/bin/bash

# swanctl.conf de r1
sudo tee /etc/netns/r1/swanctl/swanctl.conf > /dev/null <<'EOF'
connections {
    net-net {
        remote_addrs = 172.16.1.2
        local {
            auth = pubkey
            certs = r1.pem
        }
        remote {
            auth = pubkey
            id = "CN=172.16.1.2"
        }
        children {
            net-net {
            	local_ts = 10.10.10.0/24
            	remote_ts = 10.0.0.0/24
                start_action = trap
            }
        }
    }
}
EOF

# swanctl.conf de r2
sudo tee /etc/netns/r2/swanctl/swanctl.conf > /dev/null <<'EOF'
connections {
    net-net {
        remote_addrs = 172.16.1.1
        local {
            auth = pubkey
            certs = r2.pem
        }
        remote {
            auth = pubkey
            id = "CN=172.16.1.1"
        }
        children {
            net-net {
            	local_ts = 10.0.0.0/24
            	remote_ts = 10.10.10.0/24
                start_action = trap
            }
        }
    }
}
EOF
