#!/bin/bash

# Configuration pour r1
sudo ip netns exec r1 bash -c '
    sudo killall charon
    sudo killall starter
    sleep 1
    sudo mkdir -p /tmp/r1
    sudo mount --bind /tmp/r1 /run
    sudo ipsec start
    sleep 3
    sudo swanctl --load-creds
    sudo swanctl --load-conns
'

# Configuration pour r2
sudo ip netns exec r2 bash -c '
    sudo mkdir -p /tmp/r2
    sudo mount --bind /tmp/r2 /run
    sudo ipsec start
    sleep 3
    sudo swanctl --load-creds
    sudo swanctl --load-conns
'
